export default {
  id: 'classic',
  name: 'Classic',
  description: 'Traditional list-based navigation with clean colors.',
  author: 'Xzp Team',
  layout: 'list',
  columns: 1,
  cardWidth: 0,
  showStatusBar: false,
  selectionStyle: 'highlight',
  palette: {
    title: 'ice',
    section: 'steel',
    accent: 'mint',
    info: 'steel',
    ok: 'mint',
    warn: 'amber',
    error: 'red',
    text: 'white',
    muted: 'slate',
    selected: 'mint',
    card: 'slate',
    highlight: 'amber',
    surface: '',
  },
};
