export default {
  id: 'minimal',
  name: 'Minimal',
  description: 'Ultra-compact list, no borders, maximum density.',
  author: 'Xzp Team',
  layout: 'list',
  columns: 1,
  cardWidth: 0,
  showStatusBar: false,
  selectionStyle: 'highlight',
  palette: {
    title: 'white',
    section: 'white',
    accent: 'white',
    info: 'white',
    ok: 'white',
    warn: 'white',
    error: 'white',
    text: 'white',
    muted: 'slate',
    selected: 'white',
    card: 'slate',
    highlight: 'white',
    surface: '',
  },
};
