export default {
  id: 'panels',
  name: 'Panels',
  description: 'Card-based navigation with selection glow and status bar.',
  author: '@nyxur-dev',
  layout: 'grid',
  columns: 3,
  cardWidth: 14,
  showStatusBar: true,
  selectionStyle: 'border',
  palette: {
    title: 'ice',
    section: 'steel',
    accent: 'ice',
    info: 'steel',
    ok: 'mint',
    warn: 'amber',
    error: 'red',
    text: 'white',
    muted: 'slate',
    selected: 'ice',
    card: 'slate',
    highlight: 'amber',
    surface: '',
  },
};
